# docker-compose.yml
version: '3.8'

services:
  app:
    container_name: code-app-1
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: final
    volumes:
      - .:/workspaces/CODE:cached
      - ./.devcontainer/continue:/home/vscode/.continue:cached
      - /home/dev/.ssh:/home/vscode/.ssh:ro
    ports:
      - "${PORT_CONTINUE:-65432}:65432"
      - "${PORT_WEB:-8080}:8080"
    environment:
      LAMMA_HOST: "http://${HOST_LAMMA}:${PORT_LAMMA}"
      CONTINUE_PORT: "${CONTINUE_PORT}"
      TERM: xterm-256color
    networks:
      - code-network
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

networks:
  code-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16